In [82]:
from scipy.io import arff
import numpy as np
import pandas as pd
import urllib.request

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

from typing import List

np.random.seed(7)


def get_multitarget_data(name: str) -> pd.DataFrame:
    """Get multitaget regression dataset"""
    url = \
        f'https://raw.githubusercontent.com/tsoumakas/mulan/master/data/multi-target/{name}.arff'
    urllib.request.urlretrieve(url, f"{name}.arff")
    arff_data = arff.loadarff(f"{name}.arff")
    return pd.DataFrame(arff_data[0])


def as_data_frame(array: np.array, colnames: List[str]):
    df = pd.DataFrame(array)
    df.columns = colnames
    return df

In [88]:
ENB_TARGETS = ['Y1', 'Y2']
enb = get_multitarget_data('enb')

In [60]:
X, y = enb.iloc[:, :-2], enb.iloc[:, -2:]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

y_train_, y_test_ = y_train.iloc[:, 0], y_test.iloc[:, 0]

In [53]:
enb

,Relative_compactness,X1,X3,X4,X5,X6,X7,X8,Y1,Y2
0,0.98,514.5,294.0,110.25,7.0,2.0,0.0,0.0,15.55,21.33
1,0.98,514.5,294.0,110.25,7.0,3.0,0.0,0.0,15.55,21.33
2,0.98,514.5,294.0,110.25,7.0,4.0,0.0,0.0,15.55,21.33
3,0.98,514.5,294.0,110.25,7.0,5.0,0.0,0.0,15.55,21.33
4,0.90,563.5,318.5,122.50,7.0,2.0,0.0,0.0,20.84,28.28
...,...,...,...,...,...,...,...,...,...,...
763,0.64,784.0,343.0,220.50,3.5,5.0,0.4,5.0,17.88,21.40
764,0.62,808.5,367.5,220.50,3.5,2.0,0.4,5.0,16.54,16.88
765,0.62,808.5,367.5,220.50,3.5,3.0,0.4,5.0,16.44,17.11
766,0.62,808.5,367.5,220.50,3.5,4.0,0.4,5.0,16.48,16.61
767,0.62,808.5,367.5,220.50,3.5,5.0,0.4,5.0,16.64,16.03

## Multiouput regressor

In [54]:
from sklearn.multioutput import MultiOutputRegressor
from xgboost import XGBRegressor

multi_reg = MultiOutputRegressor(
  estimator = XGBRegressor()
)

multi_reg.fit(X_train, y_train)
multi_reg_pred = multi_reg.predict(X_test)

mean_squared_error(y_test, multi_reg_pred)

0.3571980210054278

## Stacking

In [55]:
from sklearn.ensemble import StackingRegressor

In [66]:
stack_reg = StackingRegressor([('first', XGBRegressor(objective='quantile')), ('second', XGBRegressor())])
stack_reg.fit(X_train, y_train_)
stack_reg_pred = stack_reg.transform(X_test)

In [67]:
stack_reg_pred

array([[15.511324 , 15.511324 ],
       [34.783104 , 34.783104 ],
       [13.947851 , 13.947851 ],
       [15.245638 , 15.245638 ],
       [15.418469 , 15.418469 ],
       [11.556831 , 11.556831 ],
       [15.368175 , 15.368175 ],
       [21.439966 , 21.439966 ],
       [12.784396 , 12.784396 ],
       [29.85384  , 29.85384  ],
       [40.032055 , 40.032055 ],
       [25.864697 , 25.864697 ],
       [29.916    , 29.916    ],
       [32.3902   , 32.3902   ],
       [12.380065 , 12.380065 ],
       [16.409222 , 16.409222 ],
       [32.88576  , 32.88576  ],
       [12.619424 , 12.619424 ],
       [24.57272  , 24.57272  ],
       [17.00491  , 17.00491  ],
       [31.777853 , 31.777853 ],
       [23.535126 , 23.535126 ],
       [14.962844 , 14.962844 ],
       [ 6.7579064,  6.7579064],
       [26.539171 , 26.539171 ],
       [33.327812 , 33.327812 ],
       [40.675606 , 40.675606 ],
       [12.492324 , 12.492324 ],
       [28.923746 , 28.923746 ],
       [12.859074 , 12.859074 ],
       [11.168164 , 11.168164 ],
       [14.569562 , 14.569562 ],
       [13.9485855, 13.9485855],
       [23.658419 , 23.658419 ],
       [14.465147 , 14.465147 ],
       [15.10608  , 15.10608  ],
       [10.703164 , 10.703164 ],
       [23.276306 , 23.276306 ],
       [13.857998 , 13.857998 ],
       [13.034675 , 13.034675 ],
       [28.965712 , 28.965712 ],
       [ 7.081013 ,  7.081013 ],
       [32.54377  , 32.54377  ],
       [13.750209 , 13.750209 ],
       [19.021118 , 19.021118 ],
       [29.369526 , 29.369526 ],
       [13.714448 , 13.714448 ],
       [26.852283 , 26.852283 ],
       [13.006243 , 13.006243 ],
       [16.955393 , 16.955393 ],
       [29.590673 , 29.590673 ],
       [15.201981 , 15.201981 ],
       [28.648722 , 28.648722 ],
       [11.4261265, 11.4261265],
       [32.66065  , 32.66065  ],
       [36.447067 , 36.447067 ],
       [24.460587 , 24.460587 ],
       [36.15623  , 36.15623  ],
       [22.748224 , 22.748224 ],
       [26.223764 , 26.223764 ],
       [35.160267 , 35.160267 ],
       [24.386364 , 24.386364 ],
       [12.084707 , 12.084707 ],
       [16.81278  , 16.81278  ],
       [10.406636 , 10.406636 ],
       [31.908993 , 31.908993 ],
       [29.728725 , 29.728725 ],
       [32.444054 , 32.444054 ],
       [36.310963 , 36.310963 ],
       [35.705208 , 35.705208 ],
       [28.459633 , 28.459633 ],
       [18.880972 , 18.880972 ],
       [23.642523 , 23.642523 ],
       [40.08531  , 40.08531  ],
       [10.438693 , 10.438693 ],
       [42.3789   , 42.3789   ],
       [18.102636 , 18.102636 ],
       [15.148612 , 15.148612 ],
       [28.833317 , 28.833317 ],
       [36.574562 , 36.574562 ],
       [28.777205 , 28.777205 ],
       [25.847649 , 25.847649 ],
       [40.66832  , 40.66832  ],
       [16.745579 , 16.745579 ],
       [31.742332 , 31.742332 ],
       [36.45394  , 36.45394  ],
       [11.875936 , 11.875936 ],
       [23.751738 , 23.751738 ],
       [39.199596 , 39.199596 ],
       [14.16175  , 14.16175  ],
       [42.024193 , 42.024193 ],
       [12.819271 , 12.819271 ],
       [14.802962 , 14.802962 ],
       [11.518094 , 11.518094 ],
       [12.389954 , 12.389954 ],
       [24.319696 , 24.319696 ],
       [16.75329  , 16.75329  ],
       [29.032753 , 29.032753 ],
       [13.178806 , 13.178806 ],
       [14.221298 , 14.221298 ],
       [11.897157 , 11.897157 ],
       [24.42204  , 24.42204  ],
       [24.363005 , 24.363005 ],
       [14.515382 , 14.515382 ],
       [15.531906 , 15.531906 ],
       [ 6.369202 ,  6.369202 ],
       [ 6.0127234,  6.0127234],
       [12.147749 , 12.147749 ],
       [25.449408 , 25.449408 ],
       [35.170807 , 35.170807 ],
       [32.179165 , 32.179165 ],
       [29.051699 , 29.051699 ],
       [12.883646 , 12.883646 ],
       [28.668587 , 28.668587 ],
       [15.292098 , 15.292098 ],
       [35.516502 , 35.516502 ],
       [15.220614 , 15.220614 ],
       [13.1635275, 13.1635275],
       [23.97228  , 23.97228  ],
       [10.441556 , 10.441556 ],
       [13.049975 , 13.049975 ],
       [18.380423 , 18.380423 ],
       [14.984103 , 14.984103 ],
       [42.18875  , 42.18875  ],
       [18.553724 , 18.553724 ],
       [12.050608 , 12.050608 ],
       [12.47812  , 12.47812  ],
       [13.956647 , 13.956647 ],
       [ 7.23387  ,  7.23387  ],
       [24.01392  , 24.01392  ],
       [26.404596 , 26.404596 ],
       [29.235165 , 29.235165 ],
       [15.132166 , 15.132166 ],
       [18.970434 , 18.970434 ],
       [15.132096 , 15.132096 ],
       [10.671804 , 10.671804 ],
       [20.15914  , 20.15914  ],
       [ 6.7564025,  6.7564025],
       [35.66842  , 35.66842  ],
       [11.111356 , 11.111356 ],
       [11.955306 , 11.955306 ],
       [32.858677 , 32.858677 ],
       [12.951805 , 12.951805 ],
       [15.316537 , 15.316537 ],
       [12.81423  , 12.81423  ],
       [17.441088 , 17.441088 ],
       [25.36073  , 25.36073  ],
       [10.595581 , 10.595581 ],
       [15.060034 , 15.060034 ],
       [11.619605 , 11.619605 ],
       [39.851524 , 39.851524 ],
       [33.39975  , 33.39975  ],
       [24.007658 , 24.007658 ],
       [12.964436 , 12.964436 ]], dtype=float32)

## ML-Ensemble

In [83]:
from mlens.ensemble import SuperLearner
from lightgbm import LGBMRegressor

ensemble = SuperLearner()
ensemble.add([
    LGBMRegressor(objective='quantile', alpha=.1), 
    LGBMRegressor(objective='quantile', alpha=.5),
    LGBMRegressor(objective='quantile', alpha=.9)
])
ensemble.fit(X_train, y_train_)
multi_quantile_pred = ensemble.predict(X_test)
as_data_frame(multi_quantile_pred, ['q_10', 'q_50', 'q_90'])

          q_10       q_50       q_90
0     8.513427  18.487013  25.697308
1    34.737083  34.950523  36.076565
2    13.856725  14.225339  14.831547
3    15.178734  15.118778  15.410851
4    15.274887  15.285230  15.316581
..         ...        ...        ...
149  11.388074  11.355670  12.460294
150  38.845280  40.151791  40.368675
151  32.023167  33.878841  33.604115
152  24.197632  25.229525  28.211617
153  12.943359  13.080950  13.301805

[154 rows x 3 columns]

## Decision tree

In [86]:
from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor()
tree_reg.fit(X_train, y_train)
tree_pred = tree_reg.predict(X_test)
as_data_frame(tree_pred, [])

In [87]:
tree_pred

array([[15.55, 21.33],
       [35.01, 33.14],
       [13.99, 14.61],
       [15.12, 19.37],
       [15.21, 19.32],
       [11.69, 13.72],
       [15.34, 19.32],
       [20.71, 25.16],
       [12.74, 16.14],
       [29.34, 33.37],
       [40.11, 40.77],
       [25.17, 26.08],
       [29.54, 33.98],
       [31.84, 31.6 ],
       [12.41, 15.28],
       [16.95, 21.16],
       [33.08, 34.11],
       [12.41, 14.92],
       [24.63, 26.37],
       [17.14, 17.15],
       [32.75, 31.  ],
       [24.37, 25.11],
       [15.09, 18.36],
       [ 6.79, 12.05],
       [26.37, 27.03],
       [33.27, 33.88],
       [40.43, 39.48],
       [12.65, 15.85],
       [29.06, 33.84],
       [13.04, 14.34],
       [11.14, 14.28],
       [14.47, 17.23],
       [14.28, 15.87],
       [24.23, 25.02],
       [14.37, 16.61],
       [15.12, 19.26],
       [10.72, 14.2 ],
       [22.89, 28.88],
       [14.17, 16.94],
       [12.73, 13.89],
       [28.03, 34.45],
       [ 7.1 , 12.23],
       [32.74, 30.53],
       [14.71, 17.51],
       [18.88, 22.07],
       [28.64, 28.95],
       [14.28, 15.87],
       [26.84, 30.17],
       [12.96, 14.34],
       [16.84, 20.56],
       [29.06, 29.34],
       [15.29, 17.82],
       [28.01, 32.92],
       [11.38, 14.54],
       [32.21, 33.76],
       [36.64, 37.01],
       [24.11, 25.84],
       [36.95, 36.87],
       [23.54, 24.61],
       [27.02, 25.63],
       [34.29, 33.31],
       [24.28, 25.68],
       [12.3 , 15.24],
       [16.56, 20.37],
       [10.43, 13.71],
       [32.74, 33.88],
       [29.68, 29.44],
       [32.26, 33.37],
       [36.86, 37.28],
       [34.29, 33.31],
       [28.03, 34.45],
       [19.13, 21.54],
       [24.24, 25.16],
       [40.68, 40.36],
       [10.43, 13.71],
       [41.3 , 44.18],
       [18.16, 20.71],
       [15.23, 18.14],
       [29.88, 28.31],
       [36.06, 34.94],
       [28.67, 32.43],
       [26.45, 27.33],
       [40.78, 39.55],
       [16.86, 20.28],
       [32.31, 32.  ],
       [36.64, 37.01],
       [11.98, 14.72],
       [24.37, 25.11],
       [39.81, 37.76],
       [13.95, 14.89],
       [41.67, 46.94],
       [12.82, 16.03],
       [15.23, 18.14],
       [11.45, 14.86],
       [12.3 , 15.44],
       [24.63, 26.37],
       [16.56, 20.37],
       [28.31, 34.15],
       [12.77, 16.22],
       [13.94, 16.7 ],
       [12.27, 14.97],
       [24.35, 25.64],
       [24.23, 25.72],
       [14.18, 16.99],
       [15.55, 21.33],
       [ 6.4 , 11.72],
       [ 6.05, 11.19],
       [12.29, 15.4 ],
       [26.84, 30.17],
       [36.45, 33.98],
       [32.48, 35.48],
       [28.05, 32.35],
       [12.88, 14.37],
       [28.67, 29.43],
       [15.16, 19.14],
       [36.71, 34.18],
       [15.18, 19.34],
       [13.17, 16.39],
       [24.32, 25.87],
       [10.43, 13.71],
       [13.02, 14.27],
       [18.16, 20.71],
       [15.08, 15.77],
       [41.73, 47.59],
       [19.34, 23.49],
       [12.17, 15.2 ],
       [12.65, 15.85],
       [14.19, 16.62],
       [ 7.1 , 12.23],
       [24.13, 26.13],
       [26.84, 30.17],
       [29.06, 33.84],
       [15.23, 17.95],
       [18.9 , 22.09],
       [15.23, 18.14],
       [10.77, 16.75],
       [20.71, 25.16],
       [ 6.79, 12.05],
       [35.56, 41.68],
       [11.1 , 14.67],
       [12.28, 15.64],
       [32.31, 32.  ],
       [13.04, 14.24],
       [15.23, 18.14],
       [12.92, 16.14],
       [17.05, 23.77],
       [25.74, 28.27],
       [10.7 , 13.75],
       [15.18, 17.63],
       [11.33, 15.  ],
       [40.19, 37.41],
       [32.68, 36.12],
       [24.26, 26.18],
       [12.93, 15.85]])